
# debug build with hot reloading
dev:
	TAURI_CONFIG='{"build":{"frontendDist":"http://localhost:1420"}}' cargo tauri build --debug 

# debug build
debug:
	cargo tauri build --debug

# production build
release:
	cargo tauri build

.PHONY: dev build
